# Default values for rook-ceph.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# clustersystem for rancher multiple app we use regexp
clustersystem: rook-ceph-system
placement:
  key: nodepool
  value: ceph
CephFilesystem:
  enabled: true
  name: myfs
  mkdirs: ""
spec:
  cephVersion:
    image:
      repository: ceph/ceph
      tag: v14.2.1-20190430
  dashboard:
    enabled: true
  dataDirHostPath: /var/lib/rook
  mon:
    allowMultiplePerNode: false
    count: 3
  network:
    hostNetwork: true
  resources:
    # important manager memory leak problem
    mgr:
      limits:
        memory: 512Mi
      requests:
        memory: 512Mi
    mon:
      limits:
        memory: 1792Mi
      requests:
        memory: 1024Mi
    osd:
      limits:
        memory: 1792Mi
      requests:
        memory: 1024Mi
  storage:
    useAllDevices: true
    useAllNodes: true
    config:
      storeType: bluestore
      osdsPerDevice: 1
    devices:
      - name: "sdb"
      - name: "sdc"
      - name: "sdd"
    # location: datacenter=dc1
