# Default values for rook-ceph.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# clustersystem for rancher multiple app we use regexp
clustersystem: rook-ceph-system
CephFilesystem:
  enabled: true
  name: myfs
  mkdirs: ""
spec:
  cephVersion:
    image:
      repository: ceph/ceph
      tag: v13.2.2-20181023
  dashboard:
    enabled: true
  dataDirHostPath: /var/lib/rook
  mon:
    allowMultiplePerNode: false
    count: 3
  network:
    hostNetwork: true
  placement:
    all:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: nodepool
              operator: In
              values:
              - ceph
  resources:
    # important manager memory leak problem
    mgr:
      limits:
        memory: 512Mi
      requests:
        memory: 512Mi
    # mon:
    #   limits:
    #     cpu: "2"
    #     memory: 2Gi
    #   requests:
    #     cpu: "2"
    #     memory: 2Gi
    # osd:
    #   requests:
    #     memory: 2Gi
  storage:
    useAllDevices: true
    useAllNodes: true
    config:
      storeType: bluestore
    devices:
      - name: "sdb"
      - name: "sdc"
      - name: "sdd"
    # location: datacenter=dc1
