apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: {{ .Values.clustername }}
  namespace: {{ .Release.Namespace }}
{{- with .Values.clusterspec }}
spec:
  {{- toYaml . | nindent 2 }}
{{- end }}
---
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: replicapool
  namespace: {{ .Release.Namespace }}
spec:
  failureDomain: host
  replicated:
    size: 3
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: {{ .Release.Namespace }}-block
provisioner: ceph.rook.io/block
parameters:
  blockPool: replicapool
  # The value of "clusterNamespace" MUST be the same as the one in which your rook cluster exist
  clusterNamespace: {{ .Release.Namespace }}
  # Specify the filesystem type of the volume. If not specified, it will use `ext4`.
  #fstype: xfs
# Optional, default reclaimPolicy is "Delete". Other options are: "Retain", "Recycle" as documented in https://kubernetes.io/docs/concepts/storage/storage-classes/
#reclaimPolicy: Retain
