apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: {{ include "rook-ceph.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  cephVersion:
    image: {{ .Values.spec.cephVersion.image.repository }}:{{ .Values.spec.cephVersion.image.tag }}
  dashboard:
    enabled: {{ .Values.spec.dashboard.enabled }}
    ssl: false
  dataDirHostPath: {{ .Values.spec.dataDirHostPath }}
  mon:
    allowMultiplePerNode: {{ .Values.spec.mon.allowMultiplePerNode }}
    count: {{ .Values.spec.mon.count }}
  network:
    hostNetwork: {{ .Values.spec.network.hostNetwork }}
  placement:
      all:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: {{ .Values.placement.key }}
                operator: In
                values:
                - {{ .Values.placement.value }}
        tolerations:
        - key: {{ .Values.placement.value }}
          operator: Exists
  resources:
    {{ toYaml .Values.spec.resources | nindent 4 | trim }}
  storage:
    {{ toYaml .Values.spec.storage | nindent 4 | trim }}
